## IMPORTANT: this is not a service to reverse proxy to; this is a proxy for snowflake
## that allows you to safely share internet with people in censored countries.
## set a small capacity so it doesn't overload your vps!

services:
    snowflake-proxy:
        network_mode: host
        image: thetorproject/snowflake-proxy:latest
        container_name: snowflake-proxy
        restart: unless-stopped
        # For a full list of Snowflake Proxy CLI parameters see
        # https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/tree/main/proxy?ref_type=heads#running-a-standalone-snowflake-proxy
        command: [ "-ephemeral-ports-range", "62950:63000", "-capacity", "5"]