version: "3"
services:
  mozhi:
    #build: .
    image: codeberg.org/aryak/mozhi:latest
    restart: unless-stopped
    ports:
      - "3012:3000"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/version || exit 1
      interval: 30s
      timeout: 5s
      retries: 2